#include "k501_aionarc/object_record.h"
#include "k501_aionarc/bytes.h"
#include "k501_aionarc/sha256.h"
#include <stdlib.h>
#include <string.h>
static bool valid_type(uint8_t t){return t>=1u&&t<=4u;}
static void digest(const uint8_t*p,size_t n,uint8_t out[32]){k501_sha256_ctx_t c;k501_sha256_init(&c);k501_sha256_update(&c,p,n);k501_sha256_final(&c,out);}
bool k501_object_record_compute_object_id(const k501_object_record_t*r,uint8_t out[32]){k501_buf_t b={0};if(!r||!out||!r->schema||!r->root_id||!r->path||r->schema_len>UINT32_MAX||r->root_id_len>UINT32_MAX||r->path_len>UINT32_MAX||!valid_type((uint8_t)r->object_type))return false;if(!k501_buf_put(&b,(const uint8_t*)K501_OID_DOMAIN,sizeof(K501_OID_DOMAIN)-1u)||!k501_buf_put_len_bytes(&b,r->schema,r->schema_len)||!k501_buf_put_len_bytes(&b,r->root_id,r->root_id_len)||!k501_buf_put_len_bytes(&b,r->path,r->path_len)||!k501_buf_put_u8(&b,(uint8_t)r->object_type)){k501_buf_free(&b);return false;}digest(b.data,b.len,out);k501_buf_free(&b);return true;}
bool k501_object_record_serialize_prefix(const k501_object_record_t*r,uint8_t**out,size_t*out_len){k501_buf_t b={0};uint8_t id[32];if(!r||!out||!out_len||!r->schema||!r->root_id||!r->path||r->schema_len>UINT32_MAX||r->root_id_len>UINT32_MAX||r->path_len>UINT32_MAX||!valid_type((uint8_t)r->object_type))return false;if(!k501_object_record_compute_object_id(r,id)||memcmp(id,r->object_id,32u)!=0)return false;if(!k501_buf_put_len_bytes(&b,r->schema,r->schema_len)||!k501_buf_put(&b,r->object_id,32u)||!k501_buf_put_len_bytes(&b,r->root_id,r->root_id_len)||!k501_buf_put_len_bytes(&b,r->path,r->path_len)||!k501_buf_put_u8(&b,(uint8_t)r->object_type)||!k501_buf_put_u8(&b,r->size_present?1u:0u)||(r->size_present&&!k501_buf_put_u64le(&b,r->size_bytes))||!k501_buf_put_u8(&b,r->content_present?1u:0u)||(r->content_present&&!k501_buf_put(&b,r->content_sha256,32u))||!k501_buf_put_i64le(&b,r->mtime_sec)||!k501_buf_put_i32le(&b,r->mtime_nsec)||!k501_buf_put_u32le(&b,r->mode)||!k501_buf_put_u8(&b,r->readable?1u:0u)){k501_buf_free(&b);return false;}*out=b.data;*out_len=b.len;return true;}
bool k501_object_record_serialize(const k501_object_record_t*r,uint8_t**out,size_t*out_len){uint8_t*prefix=NULL,*full=NULL,hash[32];size_t n=0u;if(!out||!out_len||!k501_object_record_serialize_prefix(r,&prefix,&n))return false;digest(prefix,n,hash);full=(uint8_t*)malloc(n+32u);if(!full){free(prefix);return false;}memcpy(full,prefix,n);memcpy(full+n,hash,32u);free(prefix);*out=full;*out_len=n+32u;return true;}
bool k501_object_record_decode(const uint8_t*buf,size_t len,k501_object_record_t*out,size_t*consumed){size_t p=0u,n;const uint8_t*v;uint8_t t,pres,bval;uint64_t u64;uint32_t u32;int64_t i64;int32_t i32;if(!buf||!out||!consumed)return false;memset(out,0,sizeof* out);if(!k501_get_bytes_view(buf,len,&p,&v,&n))return false;out->schema=v;out->schema_len=n;if(n!=strlen(K501_BOR_SCHEMA)||memcmp(v,K501_BOR_SCHEMA,n)!=0)return false;if(p>len||32u>len-p)return false;memcpy(out->object_id,buf+p,32u);p+=32u;if(!k501_get_bytes_view(buf,len,&p,&out->root_id,&out->root_id_len)||!k501_get_bytes_view(buf,len,&p,&out->path,&out->path_len)||!k501_get_u8(buf,len,&p,&t)||!valid_type(t))return false;out->object_type=(k501_object_type_t)t;if(!k501_get_u8(buf,len,&p,&pres)||pres>1u)return false;out->size_present=pres==1u;if(out->size_present&&!k501_get_u64le(buf,len,&p,&u64))return false;out->size_bytes=u64;if(!k501_get_u8(buf,len,&p,&pres)||pres>1u)return false;out->content_present=pres==1u;if(out->content_present){if(p>len||32u>len-p)return false;memcpy(out->content_sha256,buf+p,32u);p+=32u;}if(!k501_get_i64le(buf,len,&p,&i64)||!k501_get_i32le(buf,len,&p,&i32)||!k501_get_u32le(buf,len,&p,&u32)||!k501_get_u8(buf,len,&p,&bval)||bval>1u)return false;out->mtime_sec=i64;out->mtime_nsec=i32;out->mode=u32;out->readable=bval==1u;if(p>len||32u>len-p)return false;memcpy(out->record_hash,buf+p,32u);p+=32u;*consumed=p;return true;}
bool k501_object_record_verify(const uint8_t*buf,size_t len,k501_object_record_t*d){size_t c=0u,plen=0u;uint8_t oid[32],rh[32],*prefix=NULL;if(!k501_object_record_decode(buf,len,d,&c)||c!=len)return false;if(!k501_object_record_compute_object_id(d,oid)||memcmp(oid,d->object_id,32u)!=0)return false;if(!k501_object_record_serialize_prefix(d,&prefix,&plen))return false;digest(prefix,plen,rh);free(prefix);return memcmp(rh,d->record_hash,32u)==0;}
